### ISSUE TITLE
pywalletconnect.client.WCClientInvalidOption: publickey not found in wc v2 URI

### ISSUE THREAD

**Issue by snarflakes** [bitlogik/pyWalletConnect#10]
I'm just practicing with your intro code.  I got this error trying to connect to the latest (sign API + Auth API) React dApp (with standalone v2 client) Live app demo dapp:

React dApp (with standalone v2 client)
🔗 Live dapp demo - https://react-app.walletconnect.com/

Any ideas?

thanks,
Snarflakes

pi@homebridge:~/PiEthereumWallet $ python3 pywallet.py
Input the WalletConnect URI : wc:f3a182efaf4bc0be4e4e456defb660a9986c69217f1aadcf3874378f9102399c@2?relay-protocol=irn&symKey=1f46eef0739979250d0599deb9538ccdd2ffd6ba91f19219f5bb3445c66eb356
Traceback (most recent call last):
  File "pywallet.py", line 8, in <module>
    wallet_dapp = WCClient.from_wc_uri(string_uri)
  File "/home/pi/.local/lib/python3.7/site-packages/pywalletconnect/client.py", line 125, in from_wc_uri
    return WCv2Client.from_wc2_uri(wc_uri_str)
  File "/home/pi/.local/lib/python3.7/site-packages/pywalletconnect/client.py", line 376, in from_wc2_uri
    raise WCClientInvalidOption("publickey not found in wc v2 URI")
pywalletconnect.client.WCClientInvalidOption: publickey not found in wc v2 URI

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pywallet.py", line 11, in <module>
    wallet_dapp.close()
NameError: name 'wallet_dapp' is not defined

**Comment by bitlogik** [comment]
Thanks for reporting that. pyWalletConnect is expecting a "publicKey" argument, and this URI provides "symKey".
Seems there was a breaking change in the specs (or the officially provided examples were off), and the "publicKey" was changed to "symKey", and the key system was be changed back to a symmetric key. It was an improvement over v1, but this change might be thrown away.
We have opened a ticket to clarify this point in the WalletConnect Developers support channel.

Where did you get this URI, on which service ? Anyway, this seems in line with the current standard. The issue for now, is that the official sample were using "publicKey" a year ago, but this has changed.

**Comment by snarflakes** [comment]
Thank you and I am grateful for you and your team's python walletconnect contribution! Opens up a lot of possibilities for me.

**Comment by bitlogik** [comment]
Just to let you know, we have started to work to upgrade to this new v2 protocol. There was many breaking changes for a year, and our implementation is no more compatible. The remaining part to change are pretty consequent : WS JWT auth and an added layer in the session key exchange. So this will take a couple of days for the upgrade to be ready.

**Comment by snarflakes** [comment]
Thanks again. This is probably why I've been unsuccessful in completing "personal-sign." Walletconnect-to-Opensea just hangs, no reaction, no official login, when I send the signature using .reply. It only accepts the pairing, but not the signature.  Excited about the updates!!!

result = signed_message.signature
print(result)
#type is hexbytes need to convert to json serializable
print(type(result))
result = Web3.toJSON(result)
wclient.reply(id_request, result)

**Comment by bitlogik** [comment]
Nothing related. v1 should work. I even tested it recently with OpenSea/WalletConnect in [Uniblow](https://uniblow.org/) (an open source wallet using this library).

I think this is just an encoding issue. You need to send the result as hex string, prepended with "0x".
Since _result_ is a HexBytes object, you can just call _result.hex()_ method and it provides exactly in this format.
See here for details : https://docs.walletconnect.com/1.0/json-rpc-api-methods/ethereum

This library uses extensively standard logging functions, and when activated it provides you all the details of what happens inside. Here's what you can add at the top of your main upper program, when you develop.

```
from logging import basicConfig, DEBUG
basicConfig(level=DEBUG)
```

Then it will print out all of the detailed debug log. With this you can probably read in the printed output the server response in case of issues (e.g. in case the signature is not correct). Very helpful for debugging.

**Comment by bitlogik** [comment]
For what matters here, v2. There is now a branch named "newV2", and it works reasonably well for now. You can test it.
We'll upload soon an updated code snippet to use pyWalletConnect for v1 and v2.
 
Take care in v2, the RPC calls are encapsulated one level further.
You can do that for example to get the query data :
```
# Same as v1
id_request, method, params = self.wc_client.get_message()
# If v2, reads the inner
if method == "wc_sessionRequest":
    method = parameters["request"].get("method")
    params = parameters["request"].get("params")
```

It is like the v2 request is translated to a v1 format, decapsulated.
We chose to leave this work to the wallet, as it provides more control over the request. Also because it was done like that for a year.

**Comment by snarflakes** [comment]
> Nothing related. v1 should work. I even tested it recently with OpenSea/WalletConnect in [Uniblow](https://uniblow.org/) (an open source wallet using this library).
> 
> I think this is just an encoding issue. You need to send the result as hex string, prepended with "0x". Since _result_ is a HexBytes object, you can just call _result.hex()_ method and it provides exactly in this format. See here for details : https://docs.walletconnect.com/1.0/json-rpc-api-methods/ethereum
> 
> This library uses extensively standard logging functions, and when activated it provides you all the details of what happens inside. Here's what you can add at the top of your main upper program, when you develop.
> 
> ```
> from logging import basicConfig, DEBUG
> basicConfig(level=DEBUG)
> ```
> 
> Then it will print out all of the detailed debug log. With this you can probably read in the printed output the server response in case of issues (e.g. in case the signature is not correct). Very helpful for debugging.

**Code used**:
read_data = wclient.get_message()
        if read_data[0] is not None:
            print("\n <---- Received WalletConnect wallet query :")
            print(read_data)
            print(type(read_data))
            id_request = read_data[0]
            print(id_request)
            method = read_data[1]
            print(method)
            parameters = read_data[2]
            print(parameters)
            print("message to sign")
            print(parameters[0])
            # Detect quit
            #  v1 disconnect
            if "personal_sign" == method:
                print("personal sign")
                #result = process_signtransaction(parameters[1])
                message = encode_defunct(text=parameters[0])
                signed_message = w3.eth.account.sign_message(message, private_key=secretkey)
                print(signed_message)
                print(parameters[1])
                result = signed_message.signature
                
                print(result)
                #type is hexbytes need to convert to json serializable
                print(type(result))
                result = result.hex()
                print(type(result))
                print(result)
                wclient.reply(id_request, result)

**Example Terminal Output**:
b'p\x03\xb5\x82\xcd\xf2Un\xbb\xff\xc1\x98\ry\x03eBj\x15R\x81\xe0\xf8\x9d\x0ee\xa5\xc6\xbd\x0c\xe9\x97\x1b\xa5N~\xfd\x1aS\xc2r\xcc\x12\xbc\x10\x93k\x11G?\x1cW\x1aJ\x8c\xe8\x9e\x8e\x9e\xb5\x85W&}\x1b'
<class 'hexbytes.main.HexBytes'>
<class 'str'>
0x7003b582cdf2556ebbffc1980d790365426a155281e0f89d0e65a5c6bd0ce9971ba54e7efd1a53c272cc12bc10936b11473f1c571a4a8ce89e8e9eb58557267d1b
DEBUG:pywalletconnect.client:--> WalletConnect Replying id[1673554629789827] : result=0x7003b582cdf2556ebbffc1980d790365426a155281e0f89d0e65a5c6bd0ce9971ba54e7efd1a53c272cc12bc10936b11473f1c571a4a8ce89e8e9eb58557267d1b
Raw message: b'{"jsonrpc":"2.0","id":1673554629789827,"result":"0x7003b582cdf2556ebbffc1980d790365426a155281e0f89d0e65a5c6bd0ce9971ba54e7efd1a53c272cc12bc10936b11473f1c571a4a8ce89e8e9eb58557267d1b"}'
DEBUG:pywalletconnect.client:WalletConnect message sending to relay : {"topic":"19d46c83-b9a5-41d2-801e-368910f0b482","type":"pub","payload":"{\"data\":\"6379bef74a83cc88389d685fb02e133e1d48d764a785e79632b8046574abb02c461fefef8962f6d593675fd302c7c4e285fd988ecc7a5f79e36ce0c195579cb953d5461ecc8f31d46a195fbd5e4ad7f85feba62648f43996d257560623842de12017f8813c08e6e116b65e76aa158cb0d2f25e9e0e8ca4efc8b71df6a93767363a98a8ccfe39ac8e4b79762a91a0412493b58c52b61035b73cf19246ecb2f46656b99b516866d85d01e55fc7be3ce289f0fe61de2d8845498c4facd3cd6103bc\",\"hmac\":\"873440225836c339bc6ffac920b36a9168072200e797a6dfb74a38e4282b5cf1\",\"iv\":\"d90436e88aa84fdccf8681ee0eb17f2e\"}"}

**Comment by bitlogik** [comment]
That looks a correct use. I think the issue is now on the signature part. You don't sign the right message probably. I suppose you use the right key. I don't know what _encode_defunct_ is doing.

'personal_sign' requires to be done as the `[EIP191](https://eips.ethereum.org/EIPS/eip-191)`. Remember the input message is presented as hex string, but this is an encoding and message shall be signed in binary. In Python `bytes.fromhex(x[2:])` should do the trick, also you can use HexBytes.
The signature is :
sign( "\x19Ethereum Signed Message:\n" + len(message) + message)) ), i.e. you sign the hash = keccak256("\x19Ethereum Signed Message:\n" + len(message) + message)

Look at the personal_sign `[documentation there](https://docs.walletconnect.com/1.0/json-rpc-api-methods/ethereum#personal_sign)`.

Also you can look at the console of the browser page where the dapp runs, sometimes it gives hints about what's wrong, if you're lucky.

**Comment by snarflakes** [comment]
I've been using this methodology: [web3py](https://web3py.readthedocs.io/en/v5/web3.eth.account.html?highlight=signature#sign-a-message).
that must be for an old signature method (the absolute original? because it isn't described by an EIP)

I guess i need to learn to use this signature generation method: 
[eth-account](https://github.com/ethereum/eth-account)

This clued me in as I didn't recognize the sequence!
"The signature is :
sign( "\x19Ethereum Signed Message:\n" + len(message) + message)) ), i.e. you sign the hash = keccak256("\x19Ethereum Signed Message:\n" + len(message) + message)"

**Comment by snarflakes** [comment]
Woh, I assumed you all were using eth_account or web3.py for constructing your signatures, but I see you built it all from scratch, that is amazing.  I will study up on your methods.  My aims are twofold, I'm fascinated with learning EVM signatures ever since I attempted to do gas free approvals using signatures for my [uniswapper physical device with swappable private keys](https://github.com/snarflakes/PiEthereumWallet) . Currently though I'm trying to add identity management to the device now for use in homeless, severely mentally ill, non-mobile device using populations.  Your uniblow hardware enabled wallet clearly incorporates the identity feature i have been trying to add!  And I will spend some time studying it.  Thanks again for your help I will reach out via email!
