### ISSUE TITLE
sessionRequest timeout if dapp is opened via proxy in Firefox

### ISSUE THREAD

**Issue by oldwizard1010** [bitlogik/pyWalletConnect#11]
Somehow it works without proxy, AND it works via proxy in chromium, but breakswith proxy in firefox
.........................................
DEBUG:pywalletconnect.client:wc URI provided decoded successfully, now starting the WalletConnect client
DEBUG:pywalletconnect.client:Opening a WalletConnect client with https://z.bridge.walletconnect.org
DEBUG:pywalletconnect.tls_socket:Socket connected
DEBUG:pywalletconnect.websocket:Connecting to WebSocket Host=z.bridge.walletconnect.org PathTarget=
DEBUG:pywalletconnect.websocket:Waiting WebSocket handshake : 1th loop.
DEBUG:pywalletconnect.websocket:WebSocket connection established.
DEBUG:pywalletconnect.client:Sending a subscription request for 6c818c7a-8802-4ce7-93e0-895dcf2a6ed2.
DEBUG:pywalletconnect.client:WalletConnect message sending to relay : {"topic":"6c818c7a-8802-4ce7-93e0-895dcf2a6ed2","type":"sub","payload":""}
Connecting with the Dapp ...
DEBUG:pywalletconnect.client:Sending a subscription request for 5c570a85-5e51-4e68-b2b2-2f0c339a32eb.
DEBUG:pywalletconnect.client:WalletConnect message sending to relay : {"topic":"5c570a85-5e51-4e68-b2b2-2f0c339a32eb","type":"sub","payload":""}
DEBUG:pywalletconnect.client:Waiting for WalletConnect sessionRequest.
DEBUG:pywalletconnect.client:Closing WalletConnect link.
DEBUG:pywalletconnect.websocket:Cancelling the WebSocket reading timer
DEBUG:pywalletconnect.websocket:Closing WebSocket
DEBUG:pywalletconnect.tls_socket:Closing socket
Traceback (most recent call last):
..........................................
line 80, in <module>
    WCCLIdemo()

line 29, in WCCLIdemo
    session_data = wclient.open_session()

~/.local/lib/python3.10/site-packages/pywalletconnect/client.py", line 301, in open_session
    raise WCClientException("sessionRequest timeout")
pywalletconnect.client.WCClientException: sessionRequest timeout
...............................................
Update: does work with Librewolf, doesn't work with firefox-developer-edition

**Comment by bitlogik** [comment]
That seems very odd. The browser and the proxy shouldn't change anything, shouldn't bring any issue.
This issue is often caused by an expired session, when a session is reused. Make sure you refresh the QRcode data to get a new session. If you try to open an old session (a session already used), the client won't get the sessionRequest message, because the session is no more valid.

In the case this is browser/proxy dependent, I bet this will be the exact same issue with any other WalletConnect client, because the issue is probably on the browser side.
