### ISSUE TITLE
pyWCDemo.py failing with "Serialization failed: data did not match any variant of untagged enum Payload"

### ISSUE THREAD

**Issue by wayne-yu-anchorage** [bitlogik/pyWalletConnect#13]
Hi folks @bitlogik @omahs ,

Thank you so much for creating and sharing this Repo.
I'm trying to do something similar in Go and have been using your work as template to do the reverse-engineering.

The Python client (with the `pyWCDemo.py` driver you linked in the README) against the testing App https://react-app.walletconnect.com/ (with projectID = **f19f5c8e2b1ea7fbd382583761c167b3**) was working fine for the last few days, until yesterday 2023-Feb-08:
After the initial connection is successful, it starts to receive this message (repeatedly):
  `WebSocket Text message received : {"id":0,"jsonrpc":"2.0","error":{"code":-32700,"message":"Serialization failed: data did not match any variant of untagged enum Payload"}}`

Do you know what is happening, or have time to take a look?
Thanks 🙏

**Comment by bitlogik** [comment]
Thank you for the report. We started to investigate.

The main issue is about the WalletConnect specification. Quoting their own words, the WC team "current focus is on wallet / dapp implementation and usage docs while we are migrating v1 -> v2.". So any library or third party company trying to implement WCv2 is having a hard bad time. The documentation of the specification is very light and so messy. We spent 90% of the time to reverse-engineer their system (reading official implementation code, analysing websocket messages, console logs...) trying to understand how it works, and what to do to make a compatible client. Anyway that's part of our job after all. Just to say WC project is YOLO and I'm totally not surprised of this breaking change.

Back to the tech issue, it looks like WC dapp beefed up the controls when deserializing data received, and something sent by pyWalletConnect may be not full correct. Still, we don't really know what is "correct" in this whole system, as the running implementation is all what we have to develop a client.

**Comment by antonio-fr** [comment]
The issue turns out to be at the relay JSON-RPC level. What's missing is the "tag" field in the "irn_publish" method. This is when a payload is send to the service (to the relay server). When added, it works like before.
See the published payload definition : https://docs.walletconnect.com/2.0/specs/servers/relay/relay-server-rpc

Previous release of the official implementation didn't check thoroughly about this field in publish messages. Now it expects this.

I have to see in details what this "tag" means, I just copied the 1103 value from the official wallet implementation, and it works.

**Comment by antonio-fr** [comment]
The issue turns out to be at the relay JSON-RPC level. What's missing is the "tag" field in the "irn_publish" method. This is when a payload is send to the service (to the relay server). When added, it works like before.
See the published payload definition : https://docs.walletconnect.com/2.0/specs/servers/relay/relay-server-rpc

Previous release of the official implementation didn't check thoroughly about this field in publish messages. Now it expects this.

I have to see in details what this "tag" means, I just copied the 1103 value from the official wallet implementation, and it works.

**Comment by bitlogik** [comment]
We have identified and fixed this issue. A release is prepared. This will also benefit Uniblow, as this wallet uses pyWalletConnect underlying to be able to connect to a dapp.

**Comment by bitlogik** [comment]
Fixed by https://github.com/bitlogik/pyWalletConnect/commit/ef97996c9eb43ecdfdfca41b88c620f1bbb16e31

**Comment by wayne-yu-anchorage** [comment]
Thank you both so much for quick response and fix.
