### ISSUE TITLE
pywalletconnect.client.WCClientException: sessionRequest timeout

### ISSUE THREAD

**Issue by BondarenkoOleksandr** [bitlogik/pyWalletConnect#2]
Hello, tell me how to use this package correctly, I tried to execute the code in the example and got an error for `InvalidOption`, I removed it and tried to connect without it.
And got this error:
`pywalletconnect.client.WCClientException: sessionRequest timeout`

my WalletConnect uri like this: `wc:8d5227cb-8afb-4644-baf4-1f13750f4d71@1?bridge=https%3A%2F%2Fz.bridge.walletconnect.org&key=my_key`

**Comment by bitlogik** [comment]
Can you details what is the message string in the _WCClientInvalidOption_ exception? This should gives you a hint about what is not right in the wcURI provided. The _from_wc_uri_ method is doing heavy checks on the string input "wc" provided. And anything wrong throws a _WCClientInvalidOption_ exception (with some details provided in the exception string).
Maybe the input() adds a new line ending character at the end, or anything like that which pollutes your wc string?

About the other error, `WCClientException: sessionRequest timeout`, it happens when the WalletConnect has no sessionRequest message reply from the gateway service after GLOBAL_TIMEOUT = 8 seconds. The open_session() method subscribe to the wallet id and waits for the first sessionrequest message.
It can come a couple of reason : 
- The gateway server is busy, and don't send the sessionRequest message as expected.
- The URI wallet id was already use, and opening a new session is no more possible as the sessionRequest was already sent. From the WalletConnect design, when a user reuse a wcURI to connect, there no way to tell, but that gives a WCClientException: sessionRequest timeout because the relay sends once the sessionRequest.

This library uses standard logging functions, and when activated it provides you all the details of what happens inside. Here's what you can do in your main upper program :

```
from logging import basicConfig, DEBUG
basicConfig(level=DEBUG)
```

Then pyWalletConnect will print out all of its debug log.
You can also use your own logging system if you're confident with it.
Just keep in mind that pyWalletConnect uses extensively logger.debug() and logger.error(), which is designed to observe what is doing under the hood during an integration of this library.
