### ISSUE TITLE
SIgn Transactions BSC 

### ISSUE THREAD

**Issue by DiMiTriFrog** [bitlogik/pyWalletConnect#7]
Is there any way to use it with new Binance Smart Chain addresses?

I don't really understand the documentation and how to use it.
I would like to create a script that given a walletconnect address, connects and signs the transaction. 

How can I send it the private key to sign? 

Thanks!

**Comment by bitlogik** [comment]
It works whatever the blockchain, when the blockchain is "EVM" compatible, and has dapps which uses WalletConnect. For example this library in used [by the Uniblow desktop wallet](https://uniblow.org), and it is compatible with ETH, BSC, MATIC, FTM, OP, METIS, GMLR, MOVR, CELO, ARB and AVAX.

First thing to know : this library only manages the WalletConnect part. It manages everything from the "wc" URL, to providing you the wallet calls, and send result back. But it needs to be used with a wallet. The wallet is a JSON-RPC service that the dapp can query through an encrypted tunnel and an online relay. This library is built for the wallet part, which establishes a link with the dapp and receives requests form a web3 app.

Now, for practice. As provided in the documentation, you can start by using this minimal code snippet :
https://gist.githubusercontent.com/bitlogik/593ac797d43e10ae294b84898524cc31/raw/91fee99ec9013175b285f22b805bb9e3c09aca2d/demo.py
And in the loop, you get the queries from the dapp with the get_message() method. You can call it until an empty response. This needs to be called periodically, and this also triggers an auto reconnection (When the WebSocket is abruptly disconnected by the relay). get_message returns : `(RPCid, method, params)` or (`None, "", [])` when no data were received since the last call (or from the initial session connection).
So this way, you get the web3 calls for the wallet part.
An example if you connect to a dapp with a wrong chain id, the dapp send a _switchEhereumChain_ command to the wallet, you get : `(1654640643175980, 'wallet_switchEthereumChain', [{'chainId': '0x38'}])`
It's up to the wallet to provide the response, and then you call .reply( req_id, result_str ), with the same id as the request, and the RPC string of the reply "result". pyWalletConnect is like a JSON-RPC library, but it goes through a WalletConnect tunnel.

You understand, pyWalletConnect doesn't touch you private key, because it is only a communication library. It provides the dapp queries and you send back the response easily. For example, you get an "eth_sign" query when you read with get_message(), then once your wallet part processes the response, you provide the result back with .reply(). But pywalletconnect isn't providing anything related to the wallet part, only the WalletConnect part. It enables for the wallet part to see the WalletConnect tunnel to the dapp as a simple JSON-RPC endpoint. It takes cares of all the layers involved in this communication : WebSocket, encryption, session negotiation and management,...

If you have some budget for a specific use case, we can assist you and provide the Python code. For free, under GPLv3 licenses, we offer this library. A Web3 python library for RPCs called [pyWeb3](https://github.com/bitlogik/pyWeb3). And [Uniblow a full desktop wallet in Python](https://github.com/bitlogik/uniblow) which uses pyWalletConnect and pyWeb3 to run the EVM chains.

**Comment by bitlogik** [comment]
You can also use [the Web3py alternative](https://web3py.readthedocs.io/en/latest/quickstart.html#). It provides everything for the wallet : RPC, wallet, ECDSA, encodings,... Because the Uniblow code might be hard to understand and to use as standalone if you're not comfortable with.

**Comment by DiMiTriFrog** [comment]
I'm checking both. Because I need only a simple connect wallet and verify multiple times. 
I checked Uniblow and isnt using wallet connect for BSC and I need it hahah.

**Comment by DiMiTriFrog** [comment]
When they fix the link mac os broken I will test it.
Its weird that nobody publish any like a Python Generate Random Wallet + web3 + pywalletconnect for scrapping

**Comment by bitlogik** [comment]
Link is fixed.
Maybe because all people that are doing that are keeping it private because you don't want to share this, as it can decrease the reward or competitive advance if you make it public. And also maybe because people are coding "direct" blockchain scripts, and/or with GraphQL API, or inject in Web3, don't need for WalletConnect.
For the sake of curiosity, what is your use case?
